// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type InfoResponseCoinHistoryReceivedInner struct {

	// Имя пользователя, который отправил монеты.
	FromUser string `json:"fromUser,omitempty"`

	// Количество полученных монет.
	Amount int32 `json:"amount,omitempty"`
}

// AssertInfoResponseCoinHistoryReceivedInnerRequired checks if the required fields are not zero-ed
func AssertInfoResponseCoinHistoryReceivedInnerRequired(obj InfoResponseCoinHistoryReceivedInner) error {
	return nil
}

// AssertInfoResponseCoinHistoryReceivedInnerConstraints checks if the values respects the defined constraints
func AssertInfoResponseCoinHistoryReceivedInnerConstraints(obj InfoResponseCoinHistoryReceivedInner) error {
	return nil
}
