// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

import (
	"errors"
)

// InfoResponse содержит информацию о пользователе: баланс, инвентарь и историю транзакций.
type InfoResponse struct {
	// Количество доступных монет.
	Coins int32 `json:"coins,omitempty"`

	// Инвентарь пользователя (список предметов).
	Inventory []InfoResponseInventoryInner `json:"inventory,omitempty"`

	// История транзакций.
	CoinHistory InfoResponseCoinHistory `json:"coinHistory,omitempty"`
}

// AssertInfoResponseRequired проверяет, что обязательные поля заполнены.
func AssertInfoResponseRequired(obj InfoResponse) error {
	if obj.Coins < 0 {
		return errors.New("coins cannot be negative")
	}

	for _, item := range obj.Inventory {
		if err := AssertInfoResponseInventoryInnerRequired(item); err != nil {
			return err
		}
	}
	if err := AssertInfoResponseCoinHistoryRequired(obj.CoinHistory); err != nil {
		return err
	}

	return nil
}

// AssertInfoResponseConstraints проверяет, соблюдены ли ограничения по данным.
func AssertInfoResponseConstraints(obj InfoResponse) error {
	if obj.Coins < 0 {
		return errors.New("coins cannot be negative")
	}

	for _, item := range obj.Inventory {
		if err := AssertInfoResponseInventoryInnerConstraints(item); err != nil {
			return err
		}
	}
	if err := AssertInfoResponseCoinHistoryConstraints(obj.CoinHistory); err != nil {
		return err
	}

	return nil
}
