// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type SendCoinRequest struct {

	// Имя пользователя, которому нужно отправить монеты.
	ToUser string `json:"toUser"`

	// Количество монет, которые необходимо отправить.
	Amount int32 `json:"amount"`
}

// AssertSendCoinRequestRequired checks if the required fields are not zero-ed
func AssertSendCoinRequestRequired(obj SendCoinRequest) error {
	elements := map[string]interface{}{
		"toUser": obj.ToUser,
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSendCoinRequestConstraints checks if the values respects the defined constraints
func AssertSendCoinRequestConstraints(obj SendCoinRequest) error {
	return nil
}
