// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

import (
	"errors"
)

// InfoResponseInventoryInner содержит информацию об одном предмете в инвентаре пользователя.
type InfoResponseInventoryInner struct {
	// Тип (название) предмета.
	Type string `json:"type,omitempty"`
	// Количество предметов данного типа.
	Quantity int32 `json:"quantity,omitempty"`
}

// AssertInfoResponseInventoryInnerRequired проверяет, что обязательные поля заполнены.
func AssertInfoResponseInventoryInnerRequired(obj InfoResponseInventoryInner) error {
	if obj.Type == "" {
		return errors.New("type cannot be empty")
	}
	return nil
}

// AssertInfoResponseInventoryInnerConstraints проверяет дополнительные ограничения.
func AssertInfoResponseInventoryInnerConstraints(obj InfoResponseInventoryInner) error {
	if obj.Quantity < 0 {
		return errors.New("quantity cannot be negative")
	}
	return nil
}
