// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

import (
	"github.com/golang-jwt/jwt/v4"
)




type AuthResponse struct {

	// JWT-токен для доступа к защищенным ресурсам.
	Token string `json:"token,omitempty"`
	jwt.RegisteredClaims
}

// AssertAuthResponseRequired checks if the required fields are not zero-ed
func AssertAuthResponseRequired(obj AuthResponse) error {
	elements := map[string]interface{}{
		"token": obj.Token,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAuthResponseConstraints checks if the values respects the defined constraints
func AssertAuthResponseConstraints(obj AuthResponse) error {
	return nil
}
