// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

// InfoResponseCoinHistoryReceivedInner описывает входящую транзакцию.
type InfoResponseCoinHistoryReceivedInner struct {
	// Имя пользователя, который отправил монеты.
	FromUser string `json:"fromUser,omitempty"`
	// Количество полученных монет.
	Amount int32 `json:"amount,omitempty"`
}

// AssertInfoResponseCoinHistoryReceivedInnerRequired проверяет, что обязательные поля заполнены.
func AssertInfoResponseCoinHistoryReceivedInnerRequired(obj InfoResponseCoinHistoryReceivedInner) error {
	// Например, можно проверить, что поле Amount > 0
	return nil
}

// AssertInfoResponseCoinHistoryReceivedInnerConstraints проверяет ограничения значений полей.
func AssertInfoResponseCoinHistoryReceivedInnerConstraints(obj InfoResponseCoinHistoryReceivedInner) error {
	// Можно добавить дополнительную логику, если нужно
	return nil
}
