// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi




type InfoResponseCoinHistorySentInner struct {

	// Имя пользователя, которому отправлены монеты.
	ToUser string `json:"toUser,omitempty"`

	// Количество отправленных монет.
	Amount int32 `json:"amount,omitempty"`
}

// AssertInfoResponseCoinHistorySentInnerRequired checks if the required fields are not zero-ed
func AssertInfoResponseCoinHistorySentInnerRequired(obj InfoResponseCoinHistorySentInner) error {
	return nil
}

// AssertInfoResponseCoinHistorySentInnerConstraints checks if the values respects the defined constraints
func AssertInfoResponseCoinHistorySentInnerConstraints(obj InfoResponseCoinHistorySentInner) error {
	return nil
}
